import type { Config } from 'tailwindcss'

export default {
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './app.vue',
    './error.vue',
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#173028',
        'primary-container': '#2d463e',
        'primary-fixed': '#cce9dd',
        'primary-fixed-dim': '#b1cdc2',
        'on-primary': '#ffffff',
        'on-primary-container': '#98b3a9',
        'secondary': '#515d85',
        'secondary-container': '#c4d0ff',
        'secondary-fixed': '#dbe1ff',
        'secondary-fixed-dim': '#b9c5f3',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#4c5880',
        'tertiary': '#30273a',
        'tertiary-container': '#463d51',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#b5a8c1',
        'surface': '#fef8f3',
        'surface-container': '#f2ede8',
        'surface-container-low': '#f8f3ee',
        'surface-container-high': '#ece7e2',
        'surface-container-highest': '#e6e2dd',
        'surface-container-lowest': '#ffffff',
        'background': '#fef8f3',
        'on-surface': '#1d1b19',
        'on-surface-variant': '#424845',
        'outline': '#727975',
        'outline-variant': '#c2c8c4',
        // Emotional journey gradient stops
        'journey-crisis-from': '#1a0a0a',
        'journey-crisis-to': '#2d1520',
        'journey-awareness-from': '#2d1520',
        'journey-awareness-to': '#3a2a1a',
        'journey-process-from': '#3a2a1a',
        'journey-process-to': '#2a3a2d',
        'journey-relief-from': '#2a3a2d',
        'journey-relief-to': '#fef8f3',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
} satisfies Config
