// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026-03-22, 6:34:31 p.m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/jeremieaubut/chantalmasse-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jeremieaubut/chantalmasse-website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jeremieaubut/chantalmasse-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jeremieaubut/chantalmasse-website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jeremieaubut/chantalmasse-website/plugins/**/*.{js,ts,mjs}","/Users/jeremieaubut/chantalmasse-website/composables/**/*.{js,ts,mjs}","/Users/jeremieaubut/chantalmasse-website/utils/**/*.{js,ts,mjs}","/Users/jeremieaubut/chantalmasse-website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jeremieaubut/chantalmasse-website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/jeremieaubut/chantalmasse-website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/jeremieaubut/chantalmasse-website/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;